normalizing hcov runners

diff --git a/hcov/hcov-nl63 b/hcov/hcov-nl63
--- a/hcov/hcov-nl63
+++ b/hcov/hcov-nl63
@@ -5,6 +5,11 @@ ORGANISM=hcov-nl63
 ASSEMBLY=GCA_000853865.1_ViralProj14960_genomic
 REFNAME=AY567487.2
 
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
+    
 echo Starting ${SAMPLE} run
 
 # give us a place to work
@@ -23,7 +28,7 @@ python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-runner.py \
     --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
     --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
     --temp-dir ${PIPELINE_ROOT}/stats/temp \
-    --fastq-dir ${HOME}/fastq/zymo/ecov \
+    --fastq-dir ${HOME}/fastq \
     --skip-variant-qc \
     --skip-annotation \
     --caller bcftools \
diff --git a/hcov/hcov-panel b/hcov/hcov-panel
--- a/hcov/hcov-panel
+++ b/hcov/hcov-panel
@@ -5,6 +5,11 @@ ORGANISM=hcov-panel
 ASSEMBLY=hcov-panel
 REFNAME=panel
 
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
+    
 echo Starting ${SAMPLE} run
 
 set -e
@@ -25,7 +30,7 @@ python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-runner.py \
     --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE} \
     --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}_runner \
     --temp-dir ${HOME}/stats/temp \
-    --fastq-dir ${HOME}/fastq/zymo/ecov \
+    --fastq-dir ${HOME}/fastq \
     --skip-variant-qc \
     --skip-annotation \
     --caller bcftools \
diff --git a/hcov/sars-cov-2 b/hcov/sars-cov-2
--- a/hcov/sars-cov-2
+++ b/hcov/sars-cov-2
@@ -5,6 +5,11 @@ ORGANISM=sars-cov-2
 ASSEMBLY=GCA_009858895.3_ASM985889v3_genomic
 REFNAME=MN908947.3
 
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
+    
 # download the reference data
 if [[ ! -d ${PIPELINE_ROOT}/reference/sars-cov-2/nextclade-data ]]; then
     nextclade dataset get --name='sars-cov-2' --output-dir=${PIPELINE_ROOT}/reference/sars-cov-2/nextclade-data
@@ -17,8 +22,8 @@ mkdir -p ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}
 
 # build the pipeline
 python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-runner.py \
-    --cores 8 \
     --no-color \
+    --cores 72 \
     --sample ${SAMPLE} \
     --work-dir ${PIPELINE_ROOT} \
     --reference-dir ${PIPELINE_ROOT}/reference/${ORGANISM} \
@@ -28,9 +33,7 @@ python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-runner.py \
     --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
     --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
     --temp-dir ${PIPELINE_ROOT}/stats/temp \
-    --fastq-dir ${HOME}/fastq/zymo/ecov \
-    --skip-variant-qc \
-    --skip-annotation \
+    --fastq-dir ${HOME}/fastq \
     --caller bcftools \
     --aligner bwa \
     --preprocessor trimgalore \
