cleanup errors

diff --git a/tools/cover-all-multiple b/tools/cover-all-multiple
--- a/tools/cover-all-multiple
+++ b/tools/cover-all-multiple
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-TARGET=iontorrent
+DESTINATION_FOLDER=2022_12_15
 
-mkdir -p ${PIPELINE_ROOT}/tmp/${TARGET}
-rm -rf ${PIPELINE_ROOT}/tmp/${TARGET}/*
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
+
+mkdir -p ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}
+rm -rf ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/*
 
 for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
     LOCATION=$(dirname $FILENAME)
-    SAMPLE=$(echo $FILENAME | cut -d/ -f6)
+    SAMPLE=$(echo $FILENAME | cut -d/ -f6 | sed 's/.sorted.bam//')
 
     if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
         printf "${SAMPLE} *: calculating depth...     \r"
@@ -15,10 +20,10 @@ for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); d
     fi
 
     printf "${SAMPLE} *: building report...       \r"
-    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${PIPELINE_ROOT}/tmp/${TARGET}/${SAMPLE}_star.tsv
+    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/${SAMPLE}_star.tsv
 
     printf "${SAMPLE} *: finished                 \n"
 done
 
-echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${PIPELINE_ROOT}/tmp/${TARGET}-multiple-call-coverage.tsv
-cat ${PIPELINE_ROOT}/tmp/${TARGET}/* | grep -v '^sample' >>${PIPELINE_ROOT}/tmp/${TARGET}-multiple-call-coverage.tsv
+echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
+cat ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/* | grep -v '^sample' >>${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
diff --git a/tools/cover-all-single b/tools/cover-all-single
--- a/tools/cover-all-single
+++ b/tools/cover-all-single
@@ -1,11 +1,16 @@
 #!/usr/bin/env bash
 
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
+
 mkdir -p ${PIPELINE_ROOT}/tmp/single-call-covers
 rm -rf ${PIPELINE_ROOT}/tmp/single-call-covers/*
 
 for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
     LOCATION=$(dirname $FILENAME)
-    SAMPLE=$(echo $FILENAME | cut -d/ -f6)
+    SAMPLE=$(echo $FILENAME | cut -d/ -f6 | sed 's/.sorted.bam//')
     ORGANISM=$(echo $FILENAME | cut -d/ -f7)
 
     if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
diff --git a/tools/gene-cover-all-multiple b/tools/gene-cover-all-multiple
--- a/tools/gene-cover-all-multiple
+++ b/tools/gene-cover-all-multiple
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
-TARGET=iontorrent
+if [[ -z ${PIPELINE_ROOT} ]]; then
+    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
+    exit 1
+fi
 
 for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
     LOCATION=$(dirname $FILENAME)
-    SAMPLE=$(echo $FILENAME | cut -d/ -f6)
+    SAMPLE=$(echo $FILENAME | cut -d/ -f6 | sed 's/.sorted.bam//')
 
     if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
         echo -ne "\033[0K${SAMPLE}:*: calculating depth...\r"
