making destination_folder a full

diff --git a/tools/hcov-report b/tools/hcov-report
--- a/tools/hcov-report
+++ b/tools/hcov-report
@@ -6,12 +6,16 @@ if [[ -z ${PIPELINE_ROOT} ]]; then
 fi
 
 if [[ -z ${DESTINATION_FOLDER} ]]; then
-    echo "Missing DESTINATION_FOLDER environment variable, unable to proceed"
-    exit 1
+  echo "Missing DESTINATION_FOLDER environment variable, unable to proceed"
+  exit 1
 fi
 
-rm -rf ${PIPELINE_ROOT}/${DESTINATION_FOLDER}
-mkdir -p ${PIPELINE_ROOT}/${DESTINATION_FOLDER}
+if [[ ! -d ${DESTINATION_FOLDER} ]]; then
+  echo "DESTINATION_FOLDER doesn't exist or is not a directory, unable to proceed"
+  exit 1
+fi
+
+rm -rf ${PIPELINE_ROOT}/${DESTINATION_FOLDER}/*
 
 for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
     LOCATION=$(dirname $FILENAME)
@@ -23,7 +27,7 @@ for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); d
     fi
 
     echo -ne "\033[0K${SAMPLE}:*: building region report...\r"
-    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${PIPELINE_ROOT}/${DESTINATION_FOLDER}/${SAMPLE}_star.tsv
+    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${DESTINATION_FOLDER}/${SAMPLE}_star.tsv
 
     echo -ne "\033[0K${SAMPLE}:*: building gene report...\r"
     ./hcov-gene-depth.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz ${LOCATION}
@@ -51,5 +55,5 @@ for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); d
     echo -ne "\033[0K${SAMPLE}:*: finished.\n"
 done
 
-echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${PIPELINE_ROOT}/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
-cat ${PIPELINE_ROOT}/${DESTINATION_FOLDER}/* | grep -v '^sample' >>${PIPELINE_ROOT}/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
+echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${DESTINATION_FOLDER}/multiple-call-coverage.tsv
+cat ${DESTINATION_FOLDER}/* | grep -v '^sample' >>${DESTINATION_FOLDER}/multiple-call-coverage.tsv
